
peline{
    agent any
    stages{
       stage('Deploy') {
        steps {
        sh '''
        oc project ytuzwk-deploy-strategies
        oc start-build greeting-service --follow --wait
        '''
        }
     }
   }
}
